name: Run Calculator Tests

on: [push, pull_request]  # Trigger condition: execute on push or PR

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s src -p "*.py"
